# This workflow Builds the UFS SRWEATHER APP
name: Build SRWA

on:
# Enable the ability to manually run this workflow, as well as when the ci-aws-intel-build label is attached to a PR, and if the PR is updated
  workflow_dispatch:
  pull_request:
    branches: 
      - rrfs_ci 
    types: 
      - labeled

# Use a default login shell which loads intel/oneapi/setvars.sh, and lmod path 
defaults:
  run:
    shell: bash -l {0}

jobs:

  Build_SRWA:
    name: Build the ufs-srweather-app  
    runs-on: self-hosted 
    if: ${{ github.event.label.name == 'ci-aws-intel-build' }}

    steps:
      - name: Set Repo and Branch Variables 
        id: set_repo
        run: |
          new_branch=`git ls-remote https://github.com/${{ github.actor }}/ufs-srweather-app.git ${{ github.head_ref }}`
          if [ -n "$new_branch" ]; then
            echo "SRWA_REPO is being set to : ${{ github.actor }}/ufs-srweather-app.git" 
            echo "::set-output name=SRWA_REPO::${{ github.actor }}/ufs-srweather-app"
            echo "SRWA_BRANCH is being set to : " ${{ github.head_ref }}
            echo "::set-output name=SRWA_BRANCH::${{ github.head_ref }}"
          else
            echo "There is not a head_ref with the same name as this PR in the SRW App, the default SRW App (NOAA-GSL fork) repository will be used."
            echo "::set-output name=SRWA_REPO::NOAA-GSL/ufs-srweather-app"
            echo "There is not a similar branch name associated with this PR in the SRW App, the default SRWA App branch (rrfs_ci) will be used."
            echo "::set-output name=SRWA_BRANCH::rrfs_ci"
          fi

      - name: Clone SRWA 
        uses: actions/checkout@v3
        with: 
          repository: ${{ steps.set_repo.outputs.SRWA_REPO }}
          ref: ${{ steps.set_repo.outputs.SRWA_BRANCH }}
          path: ufs-srweather-app-${{ github.run_id }}

      - name: Checkout Externals & Delete Regional Workflow
        run: |
          cd ufs-srweather-app-${{ github.run_id }}
          ./manage_externals/checkout_externals
          rm -rf regional_workflow

      - name: Checkout 'this' version of Regional Workflow
        uses: actions/checkout@v3
        with:
          path: ufs-srweather-app-${{ github.run_id }}/regional_workflow
          clean: false
  
      - name: Build Short Range Weather App using test/build.sh
        run: |
          cd ufs-srweather-app-${{ github.run_id }}/test/
          ./build.sh aws 2>&1 | tee build_test.out
  
      - name: Get build status & Save workflow_run id of SRWA build
        id: status
        run: |
          cd ufs-srweather-app-${{ github.run_id }}/test/
          status=`tail -1 build_test.out |cut -d ' ' -f 3-`
          if [ $status == PASS ]; then
            echo ${{ github.run_id }} > ${{ github.workspace}}/run_id.txt
            exit 0
          else 
            exit 1
          fi

