# This workflow uses runs the CI for the Regional Workflow
name: Run WE2E Tests

on:
  workflow_dispatch:
  # Run this workflow after the Build SRWA workflow completes
  workflow_run:
    workflows: [Build SRWA]
    types: 
      - completed
  pull_request:
    branches:
      - rrfs_ci
    types: 
      - labeled

# Use custom shell with -l so .bash_profile is sourced which loads intel/oneapi/setvars.sh, and lmod path 
defaults:
  run:
    shell: bash -l {0}

jobs:
  
  exit-on-build-failure: 
    name: Exit this workflow if the SRWA Build failed
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.label.name == 'ci-aws-intel-WE' }}
    steps:
      - name: Exit 
        run: | 
          echo 'SRWA Build failed'
          exit 1
 
  capture-srwa-build-workflow-run-id:
    name: Save workflow_run id of SRWA build 
    # only save the SRWA build run_id if this is event that triggered this workflow 
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.label.name == 'ci-aws-intel-WE' }}
    runs-on: self-hosted

    steps: 
      - uses: actions/checkout@v3
        with:
          clean: false
      - name: Save SRWA run_id  
        run: |
          echo ${{ github.event.workflow_run.id }} > ${{ github.workspace}}/run_id.txt 

  # Run id is used for re-running WE2E tests on updates to a PR when re-buidling SRWA isn't required
  get-run-id:
    name: Get the GHA run_id of the SRWA build to pass to sequential jobs 
    runs-on: self-hosted
    if: ${{ github.event.label.name == 'ci-aws-intel-WE' }}
    outputs: 
      run-id: ${{ steps.get_run_id.outputs.run-id}}

    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
      - id: get_run_id
        run: echo "::set-output name=run-id::$(cat ${{ github.workspace}}/run_id.txt)"

  set-matrix:
    name: Set matrix of tests from machine_suites/ci.txt 
    needs: get-run-id
    runs-on: self-hosted
    if: ${{ github.event.label.name == 'ci-aws-intel-WE' }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
 
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
      - id: set-matrix
        run: | 
          echo "::set-output name=matrix::$(cat ufs-srweather-app-${{ needs.get-run-id.outputs.run-id }}/regional_workflow/tests/WE2E/machine_suites/ci.txt | jq -R -s -c 'split("\n")[:-1]')"
          echo 

  create-experiment-directory:
    needs: [ set-matrix ]
    runs-on: self-hosted
    if: ${{ github.event.label.name == 'ci-aws-intel-WE' }}
    # We use THIS workflow's run id to set a new experiment directory, not the SRWA build workflow run_id 
    steps:
      - name: Create experiment directory 
        run: |
          mkdir -p /scratch1/ci-WE2E-test/${{ github.run_id }}

  submit-all-tests:
    name: Submit experiments to ./run_WE2E_tests.sh
    needs: [ set-matrix, create-experiment-directory, get-run-id ]
    runs-on: self-hosted
    if: ${{ github.event.label.name == 'ci-aws-intel-WE' }}

    steps:
      - name: Submit all experiments (WE2E tests) 
        run: | 
          cd ufs-srweather-app-${{ needs.get-run-id.outputs.run-id }}/regional_workflow/tests/WE2E/
          module use -a /scratch1/miniconda3/contrib_miniconda3/modulefiles
          module load miniconda3/4.11.0
          conda activate regional_workflow
          ./run_WE2E_tests.sh \
            tests_file=machine_suites/ci.txt \
            machine=aws \
            account=account \
            expt_basedir=/scratch1/ci-WE2E-test/${{ github.run_id }} \
            exec_subdir=bin_intel/bin \
            cron_relaunch_intvl_mnts=01 \
            build_mod_fn=build_aws_intel

  check-overall-we2e-status:
    name: Check all of the experiments were submitted
    needs: [ set-matrix, create-experiment-directory, submit-all-tests, get-run-id ]
    runs-on: self-hosted
    if: ${{ github.event.label.name == 'ci-aws-intel-WE' }}
    steps:
      - name: Check the status of all experiments
        run: |
          echo "Check Workflow Generation/Status"
          cd ufs-srweather-app-${{ needs.get-run-id.outputs.run-id }}/regional_workflow/tests/WE2E/
          ./get_expts_status.sh expts_basedir=/scratch1/ci-WE2E-test/${{ github.run_id }}
    
  check-each-we2e-status: 
    name: Check ${{ matrix.WE2Etest }} Status
    needs: [ set-matrix, create-experiment-directory, submit-all-tests, check-overall-we2e-status, get-run-id ]
    runs-on: self-hosted
    if: ${{ github.event.label.name == 'ci-aws-intel-WE' }}
    strategy:
        fail-fast: false
        matrix:
            WE2Etest: ${{ fromJson(needs.set-matrix.outputs.matrix) }}

    steps: 
      - name: Check Workflow Status
        run: |
          cd /scratch1/ci-WE2E-test/${{ github.run_id }}/${{ matrix.WE2Etest }}
          sleep 60
          tail -40 log.launch_FV3LAM_wflow

      - name: Exit on SUCCESS/FAILURE
        run: | 
          echo "Execute script that checks for workflow status to change from IN PROGRESS to SUCCESS/FAILURE"
          cd ufs-srweather-app-${{ needs.get-run-id.outputs.run-id }}/regional_workflow/tests/WE2E/
          ./get_single_expt_status.sh expts_basedir=/scratch1/ci-WE2E-test/${{ github.run_id }} expt_name=${{ matrix.WE2Etest }}
